url: "https://ggmaths.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://ggmaths.co.uk" # the subpath of your site, e.g. /blog
title: "GG Maths" # the name of your site, e.g. ACME Corp.